### ISSUE TITLE
Adding the Golden Knights

### ISSUE THREAD

**Issue by simonxoxo** [fewieden/MMM-NHL#3]
It would be very nice if you can add the Vegas Golden Knights.
Thanks for this awesome module. :)

**Comment by fewieden** [comment]
I have no time in the next weeks to do a lot of stuff, but if you can provide me with a logo of this team and send me the three letter name of it, I will add it

**Comment by simonxoxo** [comment]
Yeah, sure I can do - thanks mate.
Hope the picture below is ok. 

the abbreviation is: 'VGK'


![vgk](https://user-images.githubusercontent.com/31259384/29944171-b4d4d0f0-8e9c-11e7-8d5e-d48afab2d1db.png)

**Comment by fewieden** [comment]
Ok hopefully the team is added correctly, I'm not able to test it currently.

Please execute the following commands to test it:
```
cd ~/MagicMirror/modules/MMM-NHL
git fetch
git checkout develop
```
then start your mirror and see if the team is showing correctly.

**Comment by simonxoxo** [comment]
Yes, seems to be working.
Thank you so much. :+1:
