### ISSUE TITLE
focus_on

### ISSUE THREAD

**Issue by xlodarx** [fewieden/MMM-NHL#8]
I am having issues on the syntax for focus_on
if I try to use an array like mentioned My MM has an error.

any examples on how to write the focus_on config?

**Comment by fewieden** [comment]
Can you post the config that you tried and then I can have a look what is wrong.

**Comment by xlodarx** [comment]
so i played with it a little and this way it shows up. However, its not focusing on the 2 teams and shows all of them on rotation.  Or maybe I didnt understand what this option is supposed to do :)

{
                        module: 'MMM-NHL',
                        position: 'bottom_left',
                        config: {
                                colored: true,
                                matches: 2,
                                rotateInterval: 20000,
                                reloadInterval: 1800000,
                                focus_on: true ['MTL', 'OTT']
                        }
                },

**Comment by xlodarx** [comment]
ok you can close it :)
Played again a little and removed "true"
now it works!
Thanks.. awesome Module :)
